general{
    lock_cmd = pidof hyprlock || hyprlock       #command to run when loacking
    #before_sleep_cmd = loginctl lock-session    #lock befour suspend
    after_sleep_cmd = hyprctl dispatch dpms on  #turn on screen after suspend
}

listener{
    timeout=1800
    on-timeout= loginctl lock-session
}

listener{
    timeout=1810
    on-timeout=hyprctl dispatch dpms off
    on-resume=hyprctl dispatch dpms on
}

listener{
    timeout = 3600
    on-timeout=systemctl suspend
}